### ISSUE TITLE
Consider writing custom properties to `:where(:root)` over `:root`

### ISSUE THREAD

**Issue by jonathantneal** [RocketCommunicationsInc/astro-design-tokens#40]
In the current CSS export of tokens, the specificity of `:root` can be reduced by using `:where(:root)`. This reduces potential issues where overrides could ship before these styles in the DOM, or where overrides could be written to the `html` tag.

```pcss
:where(:root) {
	--font-family-mono: 'Roboto Mono', system-ui, sans-serif;
	--font-family-sans: 'Roboto', system-ui, sans-serif;
}
```

**Comment by markacianfrani** [comment]
good idea! PR up
